### ISSUE TITLE
Add Nullable Check Operator

### ISSUE THREAD

**Issue by hantsy** [jakartaee/expression-language#242] opened 2024-07-22 03:52 UTC
Add a `?` to check the instance nullable and simplify the EL apply to nullable object

eg. 

```kotlin 
customer.firstName?.lowercase()
```

**Comment by markt-asf** [comment] 2024-07-22 08:37
What is the expected behaviour when `firstName` is null?
What is the expected behaviour when `firstName` is non-null?

How is this different from making `firstName` an Optional and using the new (with EL 6.0) `OptionalELResolver`?

**Comment by hantsy** [comment] 2024-07-22 10:41
It is inspired by Kotlin or typescript etc.

> What is the expected behaviour when `firstName` is null? 

return null

>What is the expected behaviour when `firstName` is non-null?

return the result to a string and lowercase
 
> How is this different from making `firstName` an Optional and using the new (with EL 6.0) `OptionalELResolver`?

I have just tried the `Optional` support in EL 6.0, but not all the existing models used `Optional` to indicate a property is nullable/optional.

**Comment by markt-asf** [comment] 2024-08-12 21:07
My reading of the EL specification is that this operator is unnecessary. Section 1.6 requires the behaviour you are requesting.

To provide a concrete example, the following test passes with the current Tomcat 11.0.x code (which also passes the EL 6.0 TCK).
```
    @Test
    public void testNull01() {
        ELProcessor processor = new ELProcessor();
        TesterBeanB beanB = new TesterBeanB();
        Assert.assertNull(beanB.getText());
        processor.defineBean("bean", beanB);
        Object result = processor.eval("bean.text.toLowerCase()");
        Assert.assertNull(result);
    }
```
If you can provide a test case (ideally in a similar style to the code above) that fails and would pass if this operator was available, I'd be happy to look at this further.

**Comment by hantsy** [comment] 2024-08-18 09:58
Looks it works well, https://github.com/hantsy/jakartaee11-sandbox/blob/master/el/src/test/java/com/example/ELExampleTest.java#L64-L78

**Comment by markt-asf** [comment] 2024-08-20 14:17
Thanks for the confirmation. I am therefore closing this issue since a new operator is not required.

**Closed by markt-asf** 2024-08-20 14:17 UTC
