### ISSUE TITLE
Some issues in tests converting LambdaExpression to FunctionalInterface

### ISSUE THREAD

**Issue by Thihup** [jakartaee/expression-language#194] opened 2023-03-10 00:06 UTC
During the implementation of Expression Language 5.0 in Joel, I've found some issues in the 'elCoerceLambdaExpressionToFunctionalInterfaceTest'

Issue 1:
```java
      ELProcessor elp2 = new ELProcessor();
      elp2.defineFunction("", "", "com.sun.ts.tests.el.spec.coercion.ELClient", "testPredicateString");
      try {
        result = elp2.eval("testPredicateString('notLambdaExpression)");
      } catch (ELException e) {
        pass[2] = true;
      }
```
The argument is missing a quote, so it fails due to a parsing error. That's probably not what the test would like to do.

Issue 2:
```java
      // Coercible lambda expression with wrong type
      ELProcessor elp3 = new ELProcessor();
      elp3.defineFunction("", "", "com.sun.ts.tests.el.spec.coercion.ELClient", "testPredicateString");
      try {
        result = elp3.eval("testPredicateLong(x -> x.equals('data'))");
      } catch (ELException e) {
        pass[3] = true;
      }
```
It defines the function "testPredicateString" but invokes the "testPredicateLong".  

Assuming issue 2 is actually an issue, I couldn't see why the test expects it to throw an exception. The lambda would invoke the `1234.equals('data')`, return false, and not throw an exception. Could you clarify if this is the expected outcome?

**Comment by markt-asf** [comment] 2023-03-10 14:34
Issue 1: Agreed. The test will pass (and should pass) but isn't testing what was intended.
Issue 2: The test should define the function "testPredicateLong". Again the test will pass (and should pass) but isn't testing what was intended.

This issue needs to be moved to the TCK project. Not sure if I can do that. I'll try that shortly.

**Comment by markt-asf** [comment] 2023-03-10 14:36
Nope. Can't move it as I don't have write access to the TCK repo. I'll leave it here but create a PR for the TCK repo against this issue.

**Comment by scottmarlow** [comment] 2023-03-20 16:14
Is this issue a TCK challenge or a request to improve the tests in the future?

Note that https://github.com/jakartaee/platform-tck/pull/1159 is a pull request for improving the test but I am not yet understanding which release of the `Jakarta EE Platform TCK` or `Expression Language TCK` is intended to be updated.

**Comment by markt-asf** [comment] 2023-03-20 17:40
I'm not viewing it as a challenge. The tests are valid in that they are expected to pass and do pass on a spec complaint implementation. It is just that they don't actually test what they were intended to test. I am treating this as a request to improve the tests for future releases (i.e. Jakarta EE 11 / EL 6.0 onwards).

https://github.com/jakartaee/platform-tck/pull/1159 is targetted at master, assuming that is the correct branch for Jakarta EE 11 development.

**Comment by markt-asf** [comment] 2024-01-11 13:04
El TCK work is now in the tckrefactor branch. https://github.com/jakartaee/platform-tck/pull/1215 fixes some issues with the original PR for this issue and a couple of additional issues found during testing.

**Comment by markt-asf** [comment] 2024-01-11 17:21
The TCK PR has been merged.

**Closed by markt-asf** 2024-01-11 17:21 UTC
